Delete most CI stuff

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -28,7 +28,7 @@ jobs:
     #        (b) it does run with Act locally (`github` doesn't exist there)
     if: >
       needs.get_commit_message.outputs.message == 1
-      && (github.repository == 'scipy/scipy' || github.repository == '')
+      && (github.repository == 'nickodell/scipy' || github.repository == '')
     runs-on: windows-2019
     steps:
       - name: Checkout
@@ -51,6 +51,7 @@ jobs:
         run: |
           pip install numpy cython pybind11 pythran meson ninja pytest pytest-xdist pytest-timeout pytest-fail-slow pooch rich_click click doit pydevtool hypothesis
           python -m pip install -r requirements/openblas.txt
+          python -m pip install pytest-json-report==1.5.0
 
       - name: Build
         run: |
@@ -60,109 +61,115 @@ jobs:
         run: |
           # test runner parallel clashes with OpenBLAS multithreading
           $env:OPENBLAS_NUM_THREADS=1
-          python dev.py test -j2 -- --durations=0 --durations-min=0.25 --fail-slow=1.0
+          python dev.py test -j2 -- --durations=0 --durations-min=0.25 --json-report --json-report-omit keywords --json-report-file ~/test-report-baseline.json
 
-
-  #############################################################################
-  full_dev_py_min_numpy_fail_slow:
-    name: fail slow, full, py3.11/npMin, dev.py
-    needs: get_commit_message
-    if: >
-      needs.get_commit_message.outputs.message == 1
-      && (github.repository == 'scipy/scipy' || github.repository == '')
-    runs-on: windows-2019
-    steps:
-      - name: Checkout
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      # Upload report file
+      - uses: actions/upload-artifact@v4
         with:
-          submodules: recursive
-      - name: Setup Python
-        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
-        with:
-          python-version: '3.11'
-          cache: 'pip'
-          cache-dependency-path: 'environment.yml'
-
-      - name: Install rtools (mingw-w64)
-        run: |
-          choco install rtools -y --no-progress --force --version=4.0.0.20220206
-          echo "c:\rtools40\ucrt64\bin;" >> $env:GITHUB_PATH
-
-      - name: pip-packages
-        run: |
-          # 1.25.2 is currently our oldest supported NumPy version
-          python -m pip install numpy==1.25.2 cython pybind11 pythran meson-python meson ninja pytest pytest-xdist pytest-timeout pytest-fail-slow pooch rich_click click doit pydevtool hypothesis
-          python -m pip install -r requirements/openblas.txt
-
-      - name: Build
-        run: |
-          python dev.py build --with-scipy-openblas
-
-      - name: Test
-        run: |
-          # test runner parallel clashes with OpenBLAS multithreading
-          $env:OPENBLAS_NUM_THREADS=1
-          python dev.py test -j2 --mode full -- --durations=0 --durations-min=1.0 --timeout=60 --fail-slow=5.0
+          name: test-report-baseline
+          path: ~/test-report-baseline.json
 
 
-  #############################################################################
-  full_build_sdist_wheel:
-    # TODO: enable ILP64 once possible
-    name: no pythran & sdist+wheel, full, py3.11/npPre, pip+pytest
-    needs: get_commit_message
-    if: >
-      needs.get_commit_message.outputs.message == 1
-      && (github.repository == 'scipy/scipy' || github.repository == '')
-    runs-on: windows-2019
-    steps:
-      - name: Checkout
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          submodules: recursive
-      - name: Setup Python
-        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
-        with:
-          python-version: '3.11'
-          cache: 'pip'
-          cache-dependency-path: 'environment.yml'
-
-      - name: Win_amd64 - install rtools
-        run: |
-          # mingw-w64
-          choco install rtools -y --no-progress --force --version=4.0.0.20220206
-          echo "c:\rtools40\ucrt64\bin;" >> $env:GITHUB_PATH
-
-      - name: Install OpenBLAS
-        shell: bash
-        run: |
-          set -xe
-          python -m pip install -r requirements/openblas.txt
-          bash tools/wheels/cibw_before_build_win.sh .
-          echo "PKG_CONFIG_PATH=${{ github.workspace }}" >> $GITHUB_ENV
-
-      - name: pip-packages
-        run: |
-          python -m pip install build delvewheel cython pybind11 meson-python meson ninja pytest pytest-xdist pytest-timeout pooch hypothesis
-          python -m pip install --pre --upgrade --timeout=60 -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple numpy
-
-      - name: Build
-        shell: bash
-        run: |
-          python -m build --no-isolation -x -Csetup-args="-Duse-pythran=false"
-
-          # Vendor openblas.dll and the DLL's it depends on into the wheel
-          # Ignore `libsf_error_state.dll` for special function error handling;
-          # it will be loaded using ctypes in scipy/special/__init__.py.
-          wheel_name=$(ls dist/*.whl)
-          openblas_dir=$(python -c"import scipy_openblas32 as sop; print(sop.get_lib_dir())")
-          delvewheel repair --add-path $openblas_dir --no-dll libsf_error_state.dll -w wheelhouse $wheel_name
-
-          python -m pip install wheelhouse/*
-
-      - name: Test
-        run: |
-          cd $RUNNER_TEMP
-          # run full test suite
-          # test runner parallel clashes with OpenBLAS multithreading
-          $env:OPENBLAS_NUM_THREADS=1
-          pytest --pyargs scipy
+#  #############################################################################
+#  full_dev_py_min_numpy_fail_slow:
+#    name: fail slow, full, py3.11/npMin, dev.py
+#    needs: get_commit_message
+#    if: >
+#      needs.get_commit_message.outputs.message == 1
+#      && (github.repository == 'scipy/scipy' || github.repository == '')
+#    runs-on: windows-2019
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+#        with:
+#          submodules: recursive
+#      - name: Setup Python
+#        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
+#        with:
+#          python-version: '3.11'
+#          cache: 'pip'
+#          cache-dependency-path: 'environment.yml'
+#
+#      - name: Install rtools (mingw-w64)
+#        run: |
+#          choco install rtools -y --no-progress --force --version=4.0.0.20220206
+#          echo "c:\rtools40\ucrt64\bin;" >> $env:GITHUB_PATH
+#
+#      - name: pip-packages
+#        run: |
+#          # 1.25.2 is currently our oldest supported NumPy version
+#          python -m pip install numpy==1.25.2 cython pybind11 pythran meson-python meson ninja pytest pytest-xdist pytest-timeout pytest-fail-slow pooch rich_click click doit pydevtool hypothesis
+#          python -m pip install -r requirements/openblas.txt
+#
+#      - name: Build
+#        run: |
+#          python dev.py build --with-scipy-openblas
+#
+#      - name: Test
+#        run: |
+#          # test runner parallel clashes with OpenBLAS multithreading
+#          $env:OPENBLAS_NUM_THREADS=1
+#          python dev.py test -j2 --mode full -- --durations=0 --durations-min=1.0 --timeout=60 --fail-slow=5.0
+#
+#
+#  #############################################################################
+#  full_build_sdist_wheel:
+#    # TODO: enable ILP64 once possible
+#    name: no pythran & sdist+wheel, full, py3.11/npPre, pip+pytest
+#    needs: get_commit_message
+#    if: >
+#      needs.get_commit_message.outputs.message == 1
+#      && (github.repository == 'scipy/scipy' || github.repository == '')
+#    runs-on: windows-2019
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+#        with:
+#          submodules: recursive
+#      - name: Setup Python
+#        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
+#        with:
+#          python-version: '3.11'
+#          cache: 'pip'
+#          cache-dependency-path: 'environment.yml'
+#
+#      - name: Win_amd64 - install rtools
+#        run: |
+#          # mingw-w64
+#          choco install rtools -y --no-progress --force --version=4.0.0.20220206
+#          echo "c:\rtools40\ucrt64\bin;" >> $env:GITHUB_PATH
+#
+#      - name: Install OpenBLAS
+#        shell: bash
+#        run: |
+#          set -xe
+#          python -m pip install -r requirements/openblas.txt
+#          bash tools/wheels/cibw_before_build_win.sh .
+#          echo "PKG_CONFIG_PATH=${{ github.workspace }}" >> $GITHUB_ENV
+#
+#      - name: pip-packages
+#        run: |
+#          python -m pip install build delvewheel cython pybind11 meson-python meson ninja pytest pytest-xdist pytest-timeout pooch hypothesis
+#          python -m pip install --pre --upgrade --timeout=60 -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple numpy
+#
+#      - name: Build
+#        shell: bash
+#        run: |
+#          python -m build --no-isolation -x -Csetup-args="-Duse-pythran=false"
+#
+#          # Vendor openblas.dll and the DLL's it depends on into the wheel
+#          # Ignore `libsf_error_state.dll` for special function error handling;
+#          # it will be loaded using ctypes in scipy/special/__init__.py.
+#          wheel_name=$(ls dist/*.whl)
+#          openblas_dir=$(python -c"import scipy_openblas32 as sop; print(sop.get_lib_dir())")
+#          delvewheel repair --add-path $openblas_dir --no-dll libsf_error_state.dll -w wheelhouse $wheel_name
+#
+#          python -m pip install wheelhouse/*
+#
+#      - name: Test
+#        run: |
+#          cd $RUNNER_TEMP
+#          # run full test suite
+#          # test runner parallel clashes with OpenBLAS multithreading
+#          $env:OPENBLAS_NUM_THREADS=1
+#          pytest --pyargs scipy
